tool:
	g++ -o tool solver.cpp tool.cpp -I/usr/local/include/stockfish -lstockfish -I/usr/local/include/cha -lcha

test:
	g++ -o test solver.cpp test.cpp -I/usr/local/include/stockfish -lstockfish -I/usr/local/include/cha -lcha

.PHONY: tool solver test
