tool:
	g++ -o tool.exe solver.cpp tool.cpp -I/usr/local/include/stockfish -lstockfish -I/usr/local/include/cha -lcha

test:
	g++ -o test.exe solver.cpp test.cpp -I/usr/local/include/stockfish -lstockfish -I/usr/local/include/cha -lcha

.PHONY: tool solver test
